name: Disable GitHub Pages

on:
  push:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  disable-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Create .nojekyll file
        run: |
          touch .nojekyll
          
      - name: Notify about Vercel deployment
        run: |
          echo "This project is deployed on Vercel, not GitHub Pages."
          echo "GitHub Pages deployment has been disabled."
          echo "Please use Vercel for deployment: https://vercel.com" 