name: Vercel Production Deployment

on:
  push:
    branches:
      - main
      - production
  
  # Enable manual triggering
  workflow_dispatch:

jobs:
  # First, cancel any GitHub Pages deployments
  cancel-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Cancel Pages Deployment
        run: |
          echo "This project is deployed on Vercel, not GitHub Pages."
          echo "Skipping GitHub Pages deployment."
          
  deploy-to-vercel:
    runs-on: ubuntu-latest
    needs: cancel-pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }} 
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          github-comment: true
          working-directory: ./ 